name: Publish Types Bundle to GitHub NPM
on: [push]

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload Library Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: library-files
          path: |
            ./
            !./node_modules
            !./.git
            !./.github
            !./.npmrc

  publish-npm:
    runs-on: ubuntu-latest
    needs: build-library
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - run: mkdir library-files

      - name: Download Library Artifacts
        uses: actions/download-artifact@v2
        with:
          name: library-files
          path: ./library-files

      - run: ls -al

      - run: ls -al
        working-directory: ./library-files

      - name: Publish to GitHub NPM
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@rcv-prod-toolkit'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./library-files

  create-release:
    runs-on: ubuntu-latest
    needs: build-library
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
